targets:
  $default:
    builders:
      mockito:mockBuilder:
        enabled: false

      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/modules/**.dart
            - lib/models/**.dart
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true